services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    networks:
      - app-network

networks:
  app-network:
    driver: bridge